name: gp_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  cloud_firestore: ^2.2.2
  firebase_core: ^1.3.0
  form_field_validator: ^1.1.0
  connectivity: ^3.0.6
  firebase_auth: ^1.4.1
  firebase_storage: ^8.1.3
  gradient_app_bar: ^0.1.3
  modal_progress_hud: ^0.1.3
  firebase_messaging: ^10.0.2
  qr_code_scanner: ^0.5.1
  url_launcher: ^6.0.6
  share: ^2.0.4
  intro_views_flutter: ^3.2.0
  intl: ^0.17.0
  flutter_swiper_null_safety: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  flutter_speed_dial: ^3.0.5
  flutter_custom_clippers: ^2.0.0
  flare_flutter: ^3.0.1
  fl_chart: ^0.36.2
  crop: ^0.5.1+1
  cached_network_image: ^3.0.0
  bottomreveal: ^2.0.0
  animator: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/
    - assets/smwallet/
    - assets/discoveryimages/
    - assets/hotel/
    - assets/icon/
    - assets/fooditem/
    - assets/flare/
    - lib/src/pages/animations/
    - lib/src/pages/animations/animation1/
    - lib/src/pages/bike/
    - lib/src/pages/blog/
    - lib/src/pages/dialogs/
    - lib/src/pages/dashboard/
    - lib/src/pages/ecommerce/
    - lib/src/pages/food/
    - lib/src/pages/grocery/
    - lib/src/pages/hotel/
    - lib/src/pages/login/
    - lib/src/pages/lists/
    - lib/src/pages/misc/
    - lib/src/pages/navigation/
    - lib/src/pages/onboarding/
    - lib/src/pages/profile/
    - lib/src/pages/quotes/
    - lib/src/pages/quiz_app/
    - lib/src/pages/todo/
    - lib/src/pages/settings/
    - lib/src/pages/travel/
    - lib/src/pages/invitation/
    - lib/src/nic_asia_clone/
    - lib/src/furniture_app/
    - assets/nicasiaassets/
    - lib/src/khalti_clone/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
